#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(digest)
  library(dplyr)
  library(readr)
  library(tibble)
})

args_full <- commandArgs(trailingOnly = FALSE)
file_arg <- args_full[grepl("^--file=", args_full)]
script_path <- if (length(file_arg) > 0L) {
  normalizePath(sub("^--file=", "", file_arg[[1]]))
} else {
  normalizePath("scripts/manuscript/write-reproducibility-metadata.R")
}
repo_root <- normalizePath(file.path(dirname(script_path), "..", ".."))
source(file.path(repo_root, "R", "path-io.R"))
output_dir <- file.path(repo_root, "results", "tables", "manuscript")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

manifest_files <- unlist(lapply(c("nba", "nfl"), function(league) {
  root <- file.path(repo_root, "data", "derived", league)
  c(
    file.path(root, "schedule_inventory.csv"),
    file.path(root, "feed_coverage_by_season.csv"),
    file.path(root, "missing_wp_games.csv"),
    if (league == "nba") file.path(root, "excluded_exhibition_games.csv") else NULL,
    file.path(root, "all_games.csv"),
    file.path(root, "all_games_enriched.csv"),
    file.path(root, paste0(2018:2024, "_games_enriched.csv")),
    vapply(2018:2024, function(season) {
      parquet <- file.path(root, paste0(season, "_paths.parquet"))
      if (file.exists(parquet)) parquet else resolve_path_file(root, season)
    }, character(1))
  )
}), use.names = FALSE)

if (any(!file.exists(manifest_files))) {
  stop(
    "Cannot freeze missing data files: ",
    paste(basename(manifest_files[!file.exists(manifest_files)]), collapse = ", ")
  )
}

manifest <- tibble(
  path = sub(paste0("^", repo_root, "/"), "", manifest_files),
  bytes = as.numeric(file.info(manifest_files)$size),
  sha256 = vapply(
    manifest_files,
    function(path) digest(path, algo = "sha256", file = TRUE),
    character(1)
  )
) |>
  arrange(path)
write_csv(
  manifest,
  file.path(output_dir, "frozen-data-manifest.csv")
)

packages <- c(
  "arrow", "data.table", "digest", "dplyr", "espnscrapeR", "ggplot2", "glue",
  "hoopR", "httr", "jsonlite", "Matrix", "matrixStats", "nflreadr",
  "readr", "scales", "tibble"
)
package_lines <- vapply(packages, function(package) {
  version <- if (requireNamespace(package, quietly = TRUE)) {
    as.character(utils::packageVersion(package))
  } else {
    "NOT INSTALLED"
  }
  paste0(package, " ", version)
}, character(1))

session_lines <- c(
  "Generated by scripts/manuscript/write-reproducibility-metadata.R",
  paste0("R ", getRversion()),
  paste0("Platform: ", R.version$platform),
  paste0("OS: ", R.version$os),
  paste0("Locale: ", Sys.getlocale()),
  "",
  "Package versions:",
  package_lines
)
writeLines(
  session_lines,
  file.path(output_dir, "session-info.txt"),
  useBytes = TRUE
)

message("Wrote frozen-data manifest and package session information.")
